[package]
name = "transfer-window"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.23.0"
glow = "0.12"
nalgebra-glm = "0.18.0"
rand = "0.8.5"

[dependencies.image]
version = "0.24"
features = ["jpeg", "png"]

[dependencies.egui_extras]
version = "0.23.0"
features = ["all_loaders"]